### ISSUE TITLE
Add theme to open-vsx marketplace

### ISSUE THREAD

**Issue by bennihtm** [pilleye/dusk-theme#1]
Hi,
I really like your theme and it would be really nice if you could add it to the FOSS Extentions marketplace open-vsx.org for use in [VSCodium](https://vscodium.com/).
You can find the instructions to do it here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

No problem if you don't want to, thanks anyways.

**Comment by pilleye** [comment]
Hey @benjaminwolkchen, unfortunately don't have the time to do that right now. It's under the MIT license, so feel free to fork and publish!
